modules:
  - client/android-app
  - client/ios-app
  - client/core
  - modules/common/server-auth
  - modules/identity/identity-common
  - modules/identity/identity-common-client
  - modules/identity/identity-server
  - server
  - modules/common/client
  - modules/sqldelight-plugin

plugins:
  - ./modules/sqldelight-plugin