modules:
  - agent
  - apps/client/android-app
  - apps/client/core
  - apps/client/ios-app
  - apps/modules/common/client
  - apps/modules/common/server-auth
  - apps/modules/identity/identity-common
  - apps/modules/identity/identity-common-client
  - apps/modules/identity/identity-server
  - apps/modules/sqldelight-plugin
  - apps/server
  - indexer
  - indexing

plugins:
  - ./apps/modules/sqldelight-plugin