modules:
  - client/android-app
  - client/ios-app
  - modules/common/client
  - modules/common/server-auth
  - modules/identity/identity-common
  - modules/identity/identity-common-client
  - modules/identity/identity-server
  - server