tasks:
  generate:
    action: !io.thisismo.sqldelight.generateSqlDelight
      moduleRootDir: ${module.rootDir}
      additionalSourceDirectories: ${pluginSettings.additionalSourceDirectories}
      outputDirectory: ${taskOutputDir}
      moduleName: ${module.name}
      packageName: ${pluginSettings.packageName}
      databaseClassName: ${pluginSettings.databaseClassName}
      dialect: ${pluginSettings.dialect}
      generateAsync: ${pluginSettings.generateAsync}
      deriveSchemaFromMigrations: ${pluginSettings.deriveSchemaFromMigrations}
      verifyMigrations: ${pluginSettings.verifyMigrations}
      treatNullAsUnknownForEquality: ${pluginSettings.treatNullAsUnknownForEquality}
      expandSelectStar: ${pluginSettings.expandSelectStar}

generated:
  sources:
    - language: kotlin
      directory: ${tasks.generate.action.outputDirectory}
