keycloak {
    authorizeUrl = "http://localhost:9090/realms/vegoapp/protocol/openid-connect/auth"
    accessTokenUrl = "http://localhost:9090/realms/vegoapp/protocol/openid-connect/token"
    clientId = "vego-identity"
    clientSecret = "mysecret"
}